### ISSUE TITLE
Query - Max Concurrent Default Changed Recently

### ISSUE THREAD

**Issue by midnightconman** [thanos-io/thanos#3063]
**Thanos, Prometheus and Golang version used**:
thanos query v0.14.0

**Object Storage Provider**:

**What happened**:
After upgrading to v0.14.0, the default value for concurrent requests went from `20` to `-1`. I think the PR that made this change was #2751 

**What you expected to happen**:
I expected the default value to be maintained (or to be recorded in release notes and other documents)

**How to reproduce it (as minimally and precisely as possible)**:
Check the default value of the `prometheus_engine_queries_concurrent_max` metric for thanos query v0.14.0

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by kakkoyun** [comment]
Hello @midnightconman, I have just seen this. I have implemented #2751. And we didn't changed the default value of that flag. The issue was the flag was not utilized at all (probably removed by mistake), the PR had just fixed that.

Where do you see that change? Maybe the issue is unrelated or we have missed something.

Or could you please explain what is the implication that you experience?

**Comment by midnightconman** [comment]
I think it's a defaults issue... and it seems it's still not working correctly. I have a metric for my thanos queriers of `prometheus_engine_queries_concurrent_max`, which currently has a value of `-1`. For normal prometheus pods, the value is `20`, which is the default.

Maybe this is just a change in the metric logic, are we supposed to have a metric for this flag setting?
