### ISSUE TITLE
Endpoint set on query is causing increase in gRPC error rate

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#4699]
We have recently switched to Thanos `v0.23.0-rc.0` for all our components on all our environments, which includes introduction of [endpoint set flow for query](https://github.com/thanos-io/thanos/pull/4421). In our `query`, we are specifying the `--store` flags by leveraging the `dnssrv+` directive. It points to a number of different components - `store`, `rule` and `receive`.

Not long after, we have noticed an increase in alerts firing for [ThanosQueryGrpcClientErrorRate](https://github.com/thanos-io/thanos/blob/main/examples/alerts/alerts.md#query). After an investigation, we've noticed that most of these errors have error code `Unimplemented`. After looking at the code, we are suspecting this is coming from the [`Info` gRPC call](https://github.com/thanos-io/thanos/blob/0d524a91ff19320ce183d404254efcd03eb8643f/pkg/query/endpointset.go#L79) which is part of the attempt to obtain metadata. However, since we also have a some components specified in the stores, which yet do not implement the `Info` gRPC service, these are returning the `Unimplemented` error back after attempting the gRPC call (and only subsequently proceeding to use store API to obtain the data as fallback).

For illustration here's the graph for `Unimplemented` error rate we've been seeing since deploying `v0.23.0-rc.0` on 9th September:
![image](https://user-images.githubusercontent.com/38492574/134642017-c19a4415-802c-4696-a123-c0e26e7a43a6.png)

All of this is causing 'false positives' due to the `Unimplemented` errors, causing the raise in error rate and triggering the alerts. I guess after Info API is implemented for all components in https://github.com/thanos-io/thanos/pull/4282#issuecomment-925778837 this should no longer be a problem, but I'm wondering whether there is any interim measure. For example, if we could do `Info` call only on components which are known to implement it at this time, otherwise go straight to back-up solution in form of Store API call.

**Comment by jr0dd** [comment]
I'm not using any custom flags here and since v0.23.0 I get spammed all day with these same false positives. I'm just changing the rule for now to ignore Unimplemented.

**Comment by matej-g** [comment]
This has for now been fixed in `v0.23.1`, so we can close it.

**Comment by sherifkayad** [comment]
@matej-g I am running Thanos v0.24.0 and still seeing this issue. Has the fix been backported to v0.24.x?

**Comment by matej-g** [comment]
Hey @sherifkayad this should be in `0.24.0`, do you have any more details? Are you getting alerts? Are these caused by `Unimplemented` error? I assume you have all your components updated to `0.24.0`, right?

**Comment by sherifkayad** [comment]
@matej-g yes, that's correct all components are upgraded to `v0.24.0` and I am still getting the alert due to `Unimplemented` errors. I re-checked the source code for version `0.24.0` and I think your changes seem to be present there .. e.g. https://github.com/thanos-io/thanos/blob/v0.24.0/pkg/query/endpointset.go .. however, the same error like initially reported by you is still happening .. I am out of ideas here ..

**Comment by sherifkayad** [comment]
@matej-g Attached a screenshot of the metric used in the alerts as well as the values associated ..
![image](https://user-images.githubusercontent.com/8362784/151832649-a15b40da-07fb-4793-9b89-7e4c494b961d.png)

**Comment by sherifkayad** [comment]
@matej-g I think I found the error .. I was using `v0.23.1` for the sidecars .. These were causing the error. Sorry for the confusion from my end. I think we are all good now.
![image](https://user-images.githubusercontent.com/8362784/151835873-a35e4b2d-3707-42ad-b4e2-a427624c2411.png)

**Comment by matej-g** [comment]
Great to hear that all is working as expected then! :blush:
