### ISSUE TITLE
inmemory cache: research other cache libraries for better performance under high concurrency

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#6762]
### Is your proposal related to a problem?

Currently, we are mainly using https://github.com/hashicorp/golang-lru `simplelru` library for inmemory cache. It is not thread safe,  so we added a lock for the whole cache https://github.com/thanos-io/thanos/blob/main/pkg/store/cache/inmemory.go#L36.

This impacts the performance a lot under high concurrency situation as each `get` and `set` operation, we need to hold the lock.

In the ideally case, we should use a thread safe cache implementation which bucketizes the whole cache into multiple buckets to improve performance under high concurrency.

### Describe the solution you'd like

https://github.com/dgraph-io/ristretto might be a good candidate to check.

**Comment by Akhil-2001** [comment]
@yeya24 This seems quite interesting. We could implement `ristretto` as another module and introduce a new case to select it as our `indexCache` [here](https://github.com/thanos-io/thanos/blob/a950eab3bb442389907d423ae476136b3b596753/pkg/store/cache/factory.go#L60). That would give us a starting point to compare the performance of the two in-memory caches. I'd love to take this up unless we need to explore other concurrent hashmap/cache options.

**Comment by yeya24** [comment]
@Akhil-2001 hey thanks for the interests.

Actually I already implemented the code to use Ristretto and currently doing tests with it. So I will take this up, sorry about this.

**Comment by Akhil-2001** [comment]
@yeya24 sure, np! Let me know if there are other issues or prospective features which you might need help with.

**Comment by aeron-gh** [comment]
Is anyone still on this? ristretto never made it into go.mod on main so I'm guessing the earlier attempt didn't land.

If it's free I'd like to pick it up. The problem is still there as described: `get` takes an exclusive `Lock` even for reads, and `FetchMultiPostings`/`FetchMultiSeries` call it once per key, so fetching N postings takes the lock N times.

My laptop is only 4 cores so wall clock benchmarks were useless here, results came out noisy and non monotonic. Mutex profiling shows it clearly though. `FetchMultiPostings` with 256 keys at GOMAXPROCS=8, `-mutexprofile`:

```
Type: delay
Showing nodes accounting for 39.98s, 100% of 39.98s total
      flat  flat%   sum%        cum   cum%
    38.74s 96.89% 96.89%     38.80s 97.03%  sync.(*Mutex).Unlock
         0     0%   100%     38.81s 97.05%  (*InMemoryIndexCache).get
         0     0%   100%     38.91s 97.32%  (*InMemoryIndexCache).FetchMultiPostings
```

So 38.8s of the ~40s of total mutex delay is that one lock, in a 17s run.

One thing worth settling before picking a library: eviction here is byte based (`maxSizeBytes`/`maxItemSizeBytes` with `curSize` accounted in `onEvict`), not item count, so whatever replaces it needs cost based eviction. That rules a few of the usual candidates out.

Two directions I could measure:

1. shard the existing hashicorp lru behind the same interface, no new dependency
2. swap in something thread safe like ristretto or otter

Any preference? Either way I'd start by adding concurrency benchmarks for this cache since there aren't any right now, so there's something to compare against.

**Comment by nielsole** [comment]
Hashicorp lru mentions in the README:
> fixed-size thread safe LRU cache

~So a simple dependency upgrade and dropping the mutex would suffice?~ EDIT: Contrary to the README, [the LRU that we use is _not_ thread safe](https://github.com/hashicorp/golang-lru/blob/9c13c57de0bedd6b3e21183b34072e417ffa69d1/simplelru/lru.go#L15)

**Comment by nielsole** [comment]
The readme hasn't been updated since this issue was opened in 2023. So I guess we might not even have to update the dependency and removing the mutex might be enough
