### ISSUE TITLE
docs: link paths differ on 'tip' vs 'v0.xx'

### ISSUE THREAD

**Issue by wbh1** [thanos-io/thanos#6889]
**Thanos, Prometheus and Golang version used**: v0.30+

**Object Storage Provider**: N/A

**What happened**: Doc links on the website are not consistent between `tip` and versions >=v0.30. For example:
https://thanos.io/tip/proposals-done/202004-embedd-cortex-frontend.md/
vs
https://thanos.io/v0.32/proposals-done/202004-embedd-cortex-frontend/
(The addition of the `.md` suffix)

The links _are_ the same for versions <=v0.29, presumably because of this Hugo section:
https://github.com/thanos-io/thanos/blob/c74a050a190486addc1ea1ca4b522462fc7ec680/website/hugo.yaml#L26-L50

**What you expected to happen**: Link paths should be the same so that users can easily switch between viewing a doc entry for different Thanos versions.

**How to reproduce it (as minimally and precisely as possible)**: Test links like the above on the live site.

**Full logs to relevant components**: N/A

**Anything else we need to know**: N/A

**Comment by wbh1** [comment]
Another example of the inconsistent link behavior potentially causing issues for users is when docs are linked to in the help text of components. For example, this flag in Query Frontend links a broken link (needs the `.md` suffix to work):
```console
      --query-frontend.vertical-shards=QUERY-FRONTEND.VERTICAL-SHARDS
                                 Number of shards to use when
                                 distributing shardable PromQL queries.
                                 For more details, you can refer to
                                 the Vertical query sharding proposal:
                                 https://thanos.io/tip/proposals-accepted/202205-vertical-query-sharding.md
```

**Comment by yeya24** [comment]
Umm, that's good catch. Then it sounds like we have to keep the Thanos versions in our hugo config update-to-date?
I wonder if we have a better way to automate this. But I think it is fine for now.
Let's update the hugo file and mention this as a required step of the Thanos release.

**Comment by kartikaysaxena** [comment]
can I work on this?

**Comment by yeya24** [comment]
@kartikaysaxena Please go ahead.

**Comment by yuvarajrece** [comment]
May I participate in working on this?

**Comment by alegmal** [comment]
@yuvarajrece looks like this issue was fixed in https://github.com/thanos-io/thanos/pull/6927?
i'm unable to reproduce the issue.

think this one can be closed unless i'm missing something.

**Comment by wbh1** [comment]
The issue is still present :(

Example:
- https://thanos.io/v0.37/proposals-done/202004-embedd-cortex-frontend/
- https://thanos.io/tip/proposals-done/202004-embedd-cortex-frontend.md/

v0.37, v0.36, and v0.35 are currently missing from the Hugo config [here](https://github.com/thanos-io/thanos/blob/fd0643206a95832ee9785641fcb94981e41a9e50/website/hugo.yaml#L26-L31)

**Comment by pdinduku** [comment]
Hi @bwplotka,

I noticed that the `permalinks` block in `thanos/website/hugo.yaml` is still being updated manually with each new release, even though `mdox` is already in use across the project.

Since there's a TODO referencing future integration, I’d like to explore automating this step — either as a temporary GitHub Action that updates permalinks on new tags, or as an extension to the existing `mdox` workflow, depending on what aligns better with the direction you have in mind.

Happy to collaborate or open a draft PR if helpful.
